name: Bug Report
description: Report a bug or issue with SpaceCat
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: SpaceCat Version
      description: What version of SpaceCat are you running?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux x86_64
        - Linux aarch64 (ARM64)
        - Windows x64
        - macOS (built from source)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your config.json (remove sensitive information like Discord webhook URLs)
      render: json
      placeholder: Paste your config.json here (remove webhook URLs!)

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Any error messages or logs
      render: text
      placeholder: Paste any error messages here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here