name: Release

permissions: write-all

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: SpaceCat ${{ github.ref_name }}
          body: |
            ## SpaceCat Release ${{ github.ref_name }}
            
            ### Downloads
            - **Linux x86_64**: spacecat-linux-x86_64
            - **Linux aarch64**: spacecat-linux-aarch64  
            - **Windows x64**: spacecat-windows-x64.exe (native build)
            - **Windows Installer**: SpaceCat-${{ github.ref_name }}-x64.msi (includes service support)
            
            ### Features
            - Astronomical observation system for SpaceCat API
            - Real-time event and image monitoring
            - Discord webhook integration
            - Mount information and meridian flip tracking
            - Autofocus analysis and reporting
            - **Windows service support** (automatically available on Windows)
            
            See [CLAUDE.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CLAUDE.md) for detailed documentation.
          draft: false
          prerelease: false

  build-linux-x64:
    name: Build Linux x86_64
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-x64-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-x64-
            ${{ runner.os }}-cargo-

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Strip binary
        run: strip target/release/spacecat

      - name: Prepare release asset
        run: cp target/release/spacecat spacecat-linux-x86_64
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./spacecat-linux-x86_64
          asset_name: spacecat-linux-x86_64
          asset_content_type: application/octet-stream

      - name: Get file info
        run: |
          ls -la spacecat-linux-x86_64
          file spacecat-linux-x86_64

  build-linux-arm64:
    name: Build Linux ARM64
    needs: create-release
    runs-on: ubuntu-24.04-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: arm64-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            arm64-cargo-

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Strip binary
        run: strip target/release/spacecat

      - name: Prepare release asset
        run: cp target/release/spacecat spacecat-linux-aarch64
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./spacecat-linux-aarch64
          asset_name: spacecat-linux-aarch64
          asset_content_type: application/octet-stream

      - name: Get file info
        run: |
          ls -la spacecat-linux-aarch64
          file spacecat-linux-aarch64

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt --check

  build-windows:
    name: Build Windows Binary and MSI Installer
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-msi-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-msi-
            ${{ runner.os }}-cargo-

      - name: Build Windows binary
        run: cargo build --release --verbose
        env:
          RUST_BACKTRACE: 1

      - name: Upload Windows binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/release/spacecat.exe
          asset_name: spacecat-windows-x64.exe
          asset_content_type: application/octet-stream

      - name: Install WiX Toolset
        run: |
          # Download and install WiX Toolset v3.14
          $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe"
          $wixInstaller = "$env:TEMP\wix314.exe"
          Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
          Start-Process -FilePath $wixInstaller -ArgumentList "/install", "/quiet", "/norestart" -Wait
          # Add WiX to PATH
          $env:PATH += ";${env:ProgramFiles(x86)}\WiX Toolset v3.14\bin"
          echo "${env:ProgramFiles(x86)}\WiX Toolset v3.14\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Extract version from tag
        id: get_version
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "::set-output name=version::$version"

      - name: Build MSI package
        run: |
          Set-Location installer
          .\build-msi.ps1 -Version $env:VERSION -SkipBuild

      - name: Upload MSI to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./installer/output/SpaceCat-${{ steps.get_version.outputs.version }}-x64.msi
          asset_name: SpaceCat-${{ steps.get_version.outputs.version }}-x64.msi
          asset_content_type: application/x-msi

      - name: Upload MSI as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ./installer/output/*.msi
