name: Build RPM Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release'
        required: false
        default: true
        type: boolean

jobs:
  build-rpm:
    name: Build RPM for Fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    
    steps:
      - name: Install build dependencies
        run: |
          dnf update -y
          dnf install -y rpm-build rpm-devel rust cargo systemd-rpm-macros \
                         openssl-devel git tar gzip make

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Create RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

      - name: Build Rust binary
        run: |
          export RUST_BACKTRACE=1
          cargo build --release --verbose

      - name: Create source tarball
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          TEMP_DIR=$(mktemp -d)
          SOURCE_DIR="$TEMP_DIR/spacecat-$VERSION"
          
          mkdir -p "$SOURCE_DIR"
          cp -r . "$SOURCE_DIR/"
          
          # Remove build artifacts and development files
          rm -rf "$SOURCE_DIR/target"
          rm -rf "$SOURCE_DIR/.git"
          rm -f "$SOURCE_DIR/.gitignore"
          rm -f "$SOURCE_DIR"/*.jpg "$SOURCE_DIR"/*.png
          
          cd "$TEMP_DIR"
          tar -czf ~/rpmbuild/SOURCES/spacecat-$VERSION.tar.gz spacecat-$VERSION
          
          # Clean up
          rm -rf "$TEMP_DIR"

      - name: Copy spec file
        run: |
          cp packaging/rpm/spacecat.spec ~/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          cd ~/rpmbuild
          rpmbuild -ba SPECS/spacecat.spec

      - name: List built packages
        run: |
          echo "Built packages:"
          find ~/rpmbuild/RPMS -name "*.rpm" -type f
          find ~/rpmbuild/SRPMS -name "*.rpm" -type f

      - name: Create RPM artifacts directory
        run: |
          mkdir -p rpm-packages
          cp ~/rpmbuild/RPMS/*/*.rpm rpm-packages/ 2>/dev/null || true
          cp ~/rpmbuild/SRPMS/*.rpm rpm-packages/ 2>/dev/null || true

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages-fedora
          path: rpm-packages/
          if-no-files-found: error

      - name: Get RPM info
        id: rpm_info
        run: |
          RPM_FILE=$(find ~/rpmbuild/RPMS -name "spacecat-*.rpm" -type f | head -n1)
          if [ -n "$RPM_FILE" ]; then
            echo "RPM_FILE=$RPM_FILE" >> $GITHUB_OUTPUT
            echo "RPM_NAME=$(basename $RPM_FILE)" >> $GITHUB_OUTPUT
            rpm -qip "$RPM_FILE"
          fi

  create-release:
    name: Create GitHub Release
    needs: build-rpm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download RPM artifacts
        uses: actions/download-artifact@v4
        with:
          name: rpm-packages-fedora
          path: rpm-packages/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: SpaceCat ${{ github.ref_name }}
          body: |
            ## SpaceCat Release ${{ github.ref_name }}
            
            ### RPM Package for Fedora/RHEL/CentOS
            
            This release includes an RPM package compatible with Fedora, RHEL, and CentOS systems.
            
            #### Installation
            
            ```bash
            # Download and install the RPM
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/spacecat-*.rpm
            sudo dnf install ./spacecat-*.rpm
            
            # Configure the service
            sudo vim /etc/spacecat/config.json
            
            # Enable and start the service
            sudo systemctl enable --now spacecat.service
            
            # Check service status
            sudo systemctl status spacecat.service
            ```
            
            #### Features
            - Systemd service running `spacecat dual-poll`
            - Automatic restarts and logging
            - Secure execution with dedicated user account
            - Configuration in `/etc/spacecat/config.json`
            - Logs in systemd journal (`journalctl -u spacecat.service`)
            
            See the [packaging documentation](https://github.com/${{ github.repository }}/tree/main/packaging) for more details.
          files: |
            rpm-packages/*.rpm
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}